language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
dist : trusty

addons:
  sonarcloud:
    organization: "sonarcloud_organization_key" # the key of the org you chose at step #3
    token:
      secure: "C+uwivLIoKknCAeRw6ZN4/5QHzDnFYa2/kTGK7+m28C7dJ4Hz/qPMF+iftbGl88/EKfRyWuLUkoLsdACQqXVkKrTuTmonCLhPkm4gyFar4jxWlRQwbGPkiZe07+7cxPKjyi52Uk8fUCUcEeen/r/hSRykfMrvJMbxwSaIIoHm5BUeKpUJD0U+y9pN4LdRRQAL4jAmJf0wDQxzHIKyG0pTaXSHpKb6gUvkLrNiyFIPV+rrdAd8keIAMpsaLUjOxmoi3fISQrQ1JjRQstp7Pop0AwL/pJau5YDODltKNsLAi5Z43fmRFAMopwe/gE7CBR0KqcBQLx+Gc+RvADfPequjh95BVdrMl9dlpsK5tVYd8BVU+gLf6SVUIYsG5VxZaLtm9kfhYPP1rcISQpATUq+R1uolqiQtqJ2eN6Ghz48nDyQuLEuz99S6Sk7HjRRu2q4ng7DzlrB/hIFQ4lRViD4fGeRXNQ/rAGwTCZ/fbRE1ij/aFUIavOHJfGAPKsiDjeLYghiQq5CYlYJfGmlCen0Xgwcb5/Tbj6Asis4YnEzZ9/zoZPThtK/2qVJ/jxlUfdTXyVenmYaBFnLP2sCZEJuwUGrpcbWcr2NATAq4bsQDE9UEa5j0wBasG9ToPJhnprrX3qbMroEB1HPod4pmMrmpi/IeS6fzMuQvkYn44QUlek="
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
