
[project]
name = "rigger-nx"

[[env]]
  name = "res"
  [env.res.vars] 
    base_include = "fundation"
    port         = 80

[[env]]
  name = "dev"
  [env.res.vars]
    base_include = "fundation"


[[env]]
  name = "demo"
  mix  = ["base"]


[[system]]
name : "init"
[system.limit]
envs = "demo,online"
passwd = "123"
[system.res]
